# SOS24 — апстримы в K8s NodePort (3 control-plane ноды, HA).
upstream sos24_api {
    server 10.10.38.11:30030 max_fails=2 fail_timeout=10s;
    server 10.10.38.12:30030 max_fails=2 fail_timeout=10s;
    server 10.10.38.13:30030 max_fails=2 fail_timeout=10s;
}
upstream sos24_admin {
    server 10.10.38.11:30035 max_fails=2 fail_timeout=10s;
    server 10.10.38.12:30035 max_fails=2 fail_timeout=10s;
    server 10.10.38.13:30035 max_fails=2 fail_timeout=10s;
}
